### ISSUE TITLE
general theme improvements

### ISSUE THREAD

**Issue by benharri** [tildeclub/site#4]
some of the things i've been thinking of:

- improve distinction for `<pre>` elements
- make the homepage fit better on mobile without horizontal scrolling

**Comment by alanpaulprice** [comment]
I'll have a go at this.

**Comment by kniziol** [comment]
Is it still available? I can work on it.

**Comment by deepend-tildeclub** [comment]
Things are definitely improving.. not sure why on mobile the table doesn't auto adjust as well as it does on desktop.  On desktop its doing what you'd think it should do on mobile.. where the right column drops below the bottom of the left with small screen size.  But on mobile it doesn't  seem to want to work.   I'm at a loss on that one.

**Comment by kittenmilk** [comment]
the mobile now looks great, although if there are still any theme improvements to be made i’m definitely down to work on them

**Comment by deepend-tildeclub** [comment]
We are always open to suggestions.  

> the mobile now looks great, although if there are still any theme improvements to be made i’m definitely down to work on them

**Comment by deepend-tildeclub** [comment]
@audiodude    I am in the process of trying to improve the way the user list shows up on the main page.   Do you know how to format the user list so its multiple columns instead of one huge straight down list.  Would like to fill the space I moved it to.   The way I'm thinking of going is on my tilde page
https://tilde.club/~deepend/tcweb

Hopefully you know because I suck at CSS :P

**Comment by audiodude** [comment]
The key is to use a flexbox. I'd be happy to have a crack at it.

**Comment by deepend-tildeclub** [comment]
sure. I can push my changes if you like?

**Comment by audiodude** [comment]
@deepend-tildeclub You can push them to a branch and I can just checkout that branch and put further edits there.
